name: .NET

on:
    push:
        branches: [master]

jobs:
    build:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v2
            - name: Add msbuild to PATH
              uses: microsoft/setup-msbuild@v1.1
            - name: Setup NuGet
              uses: NuGet/setup-nuget@v1.0.2
            - name: Restore NuGet Packages
              run: nuget restore Editor.sln
            - name: Build
              run: msbuild Editor.csproj -t:rebuild -verbosity:diag -property:Configuration=Release
            - name: Upload Artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: artifact
                  path: ./bin/Release/x64/
